### ISSUE TITLE
UFPCA Error

### ISSUE THREAD

**Issue by Msalehi237** [StevenGolovkine/FDApy#11]
In the examples for fpca "plot_fpca_1d.py" line 60:

scores = ufpca.transform(data, method='NumInt')

Runs into an error and returns:
ValueError: operands could not be broadcast together with shapes (100,1,1) (49,3,101)

**Comment by StevenGolovkine** [comment]
Hi,

I am well aware of this error. This is due to a re-implementation of the `integrate` function to generalise to higher dimensional domains.
Fixing this error is not as straightforward as I was thinking. If you can fix it, I'll be happy to add your code into the package (function `_numerical_integration` in `UFPCA` class).

**Comment by StevenGolovkine** [comment]
I wrote a quick fix to this error. It should work, but I did not do extensive testing.

**Comment by StevenGolovkine** [comment]
This has been fixed.
I close the issue.
